# Generated by Django 5.0.6 on 2024-06-19 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 6, 19, 13, 4, 8, 361113, tzinfo=datetime.timezone.utc), help_text='Укажите дату создания статьи', verbose_name='Дата создания'),
        ),
    ]
