# Generated by Django 5.0.6 on 2024-06-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Укажите дату создания статьи', verbose_name='Дата создания'),
        ),
    ]
