# Generated by Django 5.0.6 on 2024-06-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="purchase_price",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(
                default=0, help_text="Введите стоимость товара", verbose_name="Цена"
            ),
            preserve_default=False,
        ),
    ]
